projectId: app-w2eH5yYLtX3rs4N5tUZ2hF
appName: bigmac
description: This is a sample application
version: "1.0"
hostName: example.test
clusterURL: default
clusterIPs:
- 190.89.89.0
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    avgReplicas: 3
    minReplicas: 3
    maxReplicas: 3
    dockerImage: shenali-sj/cart
    containerPort: 8080
  OrderService:
    serviceName: orderservice
    avgReplicas: 2
    minReplicas: 1
    maxReplicas: 4
    dockerImage: shenali-sj/order
    containerPort: 8080
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    avgReplicas: 4
    minReplicas: 3
    maxReplicas: 5
    dockerImage: shenali-sj/user
    containerPort: 8080
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
